<a href="https://colab.research.google.com/github/BharatXBhalla/Deep-Learning-CDAC/blob/main/Rnn/SimpleRnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense,SimpleRNN

In [22]:
def rnnModels():
  model=Sequential()
  model.add(SimpleRNN(5,input_shape=(3,2),activation="relu"))
  model.add(Dense(1,activation="relu"))
  model.compile(loss="mean_squared_error",optimizer="adam")
  return model

In [23]:
model=rnnModels()

In [24]:
model.weights

[<tf.Variable 'simple_rnn_3/simple_rnn_cell_3/kernel:0' shape=(2, 5) dtype=float32, numpy=
 array([[ 0.45393574,  0.0614211 ,  0.16106176,  0.44295025,  0.44574344],
        [ 0.30805528, -0.2578615 , -0.50351846, -0.06719482,  0.5266248 ]],
       dtype=float32)>,
 <tf.Variable 'simple_rnn_3/simple_rnn_cell_3/recurrent_kernel:0' shape=(5, 5) dtype=float32, numpy=
 array([[ 0.19620872,  0.502025  , -0.32550788,  0.7152034 , -0.303318  ],
        [ 0.75113255, -0.19612873,  0.59457433,  0.13401857, -0.16079137],
        [ 0.3843506 , -0.51879025, -0.57494   ,  0.1937135 ,  0.46373534],
        [-0.02759676,  0.41177034,  0.3416285 ,  0.21977764,  0.8152738 ],
        [-0.49881372, -0.52039045,  0.3053851 ,  0.6202388 , -0.04921915]],
       dtype=float32)>,
 <tf.Variable 'simple_rnn_3/simple_rnn_cell_3/bias:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_3/kernel:0' shape=(5, 1) dtype=float32, numpy=
 array([[ 0.11528301],
        [ 0

In [25]:
wx =model.get_weights()[0]
wh=model.get_weights()[1]
bh=model.get_weights()[2]
wy=model.get_weights()[3]
by=model.get_weights()[4]

In [26]:
wx

array([[ 0.45393574,  0.0614211 ,  0.16106176,  0.44295025,  0.44574344],
       [ 0.30805528, -0.2578615 , -0.50351846, -0.06719482,  0.5266248 ]],
      dtype=float32)

In [27]:
wh

array([[ 0.19620872,  0.502025  , -0.32550788,  0.7152034 , -0.303318  ],
       [ 0.75113255, -0.19612873,  0.59457433,  0.13401857, -0.16079137],
       [ 0.3843506 , -0.51879025, -0.57494   ,  0.1937135 ,  0.46373534],
       [-0.02759676,  0.41177034,  0.3416285 ,  0.21977764,  0.8152738 ],
       [-0.49881372, -0.52039045,  0.3053851 ,  0.6202388 , -0.04921915]],
      dtype=float32)

In [28]:
bh

array([0., 0., 0., 0., 0.], dtype=float32)

In [31]:
wy

array([[ 0.11528301],
       [ 0.05118752],
       [ 0.43215966],
       [-0.40036392],
       [-0.9010978 ]], dtype=float32)

In [30]:
by

array([0.], dtype=float32)

In [33]:
print(f'wx= {wx} , wy ={wy} , bh={bh}, wh={wh} , by = {by}')

wx= [[ 0.45393574  0.0614211   0.16106176  0.44295025  0.44574344]
 [ 0.30805528 -0.2578615  -0.50351846 -0.06719482  0.5266248 ]] , wy =[[ 0.11528301]
 [ 0.05118752]
 [ 0.43215966]
 [-0.40036392]
 [-0.9010978 ]] , bh=[0. 0. 0. 0. 0.], wh=[[ 0.19620872  0.502025   -0.32550788  0.7152034  -0.303318  ]
 [ 0.75113255 -0.19612873  0.59457433  0.13401857 -0.16079137]
 [ 0.3843506  -0.51879025 -0.57494     0.1937135   0.46373534]
 [-0.02759676  0.41177034  0.3416285   0.21977764  0.8152738 ]
 [-0.49881372 -0.52039045  0.3053851   0.6202388  -0.04921915]] , by = [0.]


In [37]:
x=np.array([1,2,3,4,5,6])

In [38]:
x

array([1, 2, 3, 4, 5, 6])

In [40]:
x_input=np.reshape(x,[1,3,2])
y_pred=model.predict(x_input)
y_pred

array([[0.]], dtype=float32)

In [45]:
m=5
h0=np.zeros(m)
h1=np.dot(x[0],wx) +h0+bh
h2=np.dot(x[1],wx)+np.dot(h1,wh)+bh
h3=np.dot(x[2],wx) +np.dot(h2,wh)+bh
output=np.dot(h3,wy)+by
print(f'h1 = {h1} , h2= {h2} , h3={h3}')

h1 = [[ 0.45393574  0.0614211   0.16106176  0.44295025  0.44574344]
 [ 0.30805528 -0.2578615  -0.50351846 -0.06719482  0.5266248 ]] , h2= [[ 0.87041027  0.20555872  0.40573026  1.62380622  1.15780068]
 [ 0.0285046  -0.35099637 -0.83326855  0.2657012   0.68707128]] , h3=[[ 1.22059516  0.43655297  0.99712283  3.13250444  2.49517935]
 [-0.00420644 -0.50627986 -0.94885541  0.09489016  1.42405172]]
